name: Setup kubecfg CLI
description: A GitHub Action for running kubecfg commands
author: Kingdon Barrett
branding:
  color: blue
  icon: command
inputs:
  version:
    description: "Kubecfg version e.g. 0.18.0 (defaults to latest stable release)"
    required: false
runs:
  using: composite
  steps:
    - name: "Download kubecfg binary to tmp"
      shell: bash
      run: |
          VERSION=0.18.0
          if [ -z $VERSION ]; then
            VERSION=$(curl https://api.github.com/repos/bitnami/kubecfg/releases/latest -sL | grep tag_name | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
          fi
          BIN_URL="https://github.com/bitnami/kubecfg/releases/download/v${VERSION}/kubecfg-linux-amd64"
          curl -sL ${BIN_URL} -o /tmp/kubecfg
          chmod +x /tmp/kubecfg
    - name: "Add kubecfg binary to /usr/local/bin"
      shell: bash
      run: |
        sudo cp /tmp/kubecfg /usr/local/bin
    - name: "Cleanup tmp"
      shell: bash
      run: |
        rm -f /tmp/kubecfg
    - name: "Verify correct installation of binary"
      shell: bash
      run: |
        kubecfg version
